[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5062

; LiveKit SIP Trunk Configuration
[livekit-trunk]
type=endpoint
context=livekit-inbound
transport=transport-udp
disallow=all
allow=ulaw
allow=alaw
allow=opus
aors=livekit-trunk
direct_media=no
trust_id_inbound=yes
from_domain=livekit-sip

[livekit-trunk]
type=aor
contact=sip:livekit-sip:5060

[livekit-trunk]
type=identify
endpoint=livekit-trunk
match=livekit-sip

; SIP Speaker Endpoints
[1001]
type=endpoint
context=default
transport=transport-udp
#disallow=all
allow=ulaw
allow=alaw
auth=auth1001
aors=1001
direct_media=no
force_rport=yes
rewrite_contact=yes
ice_support=yes

[auth1001]
type=auth
auth_type=userpass
username=1001
password=Breakout35

[1001]
type=aor
max_contacts=1
remove_existing=yes

[1002]
type=endpoint
context=default
transport=transport-udp
# disallow=all
allow=ulaw
allow=alaw
auth=auth1002
aors=1002
direct_media=no
force_rport=yes
rewrite_contact=yes
ice_support=yes

[auth1002]
type=auth
auth_type=userpass
username=1002
password=Breakout35

[1002]
type=aor
max_contacts=1
remove_existing=yes

[system] 
type=system 
allowguest=no